/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import control.VormControle;
import entity.Vorm;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Leon
 */
public class HoofdFrame extends javax.swing.JFrame {

    private VormControle vormControle;
    
    /**
     * Creates new form HoofdFrame
     */
    public HoofdFrame(VormControle vormControle) {
        this.vormControle = vormControle;
        initComponents();
        //Zet scherm in het midden
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    /**
     * Ververs de lijst met vormen
     */
    public void verversScherm() {
        DefaultListModel<Vorm> model = new DefaultListModel<>();
        int x = 0;
        for (Vorm vorm : vormControle.getAlleVormen()) { //Vul de lijst
            model.add(x, vorm);
            x++;
        }
        //Set model
        vormLijst.setModel(model);
        
        //Set de totaal inhoud
        totaleInhoudField.setText(String.valueOf(vormControle.totaalInhoud()));
    }
    
    /**
     * Show JOptionPane message
     * @param message message
     * @param titel titel
     * @param typeMessage Type message 
     */
    private void showMessage(String message, String titel) {
        JOptionPane.showMessageDialog(this, message, titel, JOptionPane.ERROR_MESSAGE);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        vormLabel = new javax.swing.JLabel();
        vormComboBox = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        inhoudLabel = new javax.swing.JLabel();
        inhoudField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        totaleInhoudLabel = new javax.swing.JLabel();
        totaleInhoudField = new javax.swing.JTextField();
        vormButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lijstOpslaanButton = new javax.swing.JButton();
        lijstLadenButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vormLijst = new javax.swing.JList();
        verwijderVormButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leon Stam, 2058473, 10-2013");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        vormLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        vormLabel.setText("Vorm");

        vormComboBox.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        vormComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bol", "Blok", "Cilinder" }));

        inhoudLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        inhoudLabel.setText("Inhoud");

        inhoudField.setEditable(false);
        inhoudField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        totaleInhoudLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        totaleInhoudLabel.setText("Totale Inhoud");

        totaleInhoudField.setEditable(false);
        totaleInhoudField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        vormButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        vormButton.setText("Voeg toe!");
        vormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vormButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vormComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(vormButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inhoudField)
                    .addComponent(jSeparator2)
                    .addComponent(totaleInhoudField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vormLabel)
                            .addComponent(inhoudLabel)
                            .addComponent(totaleInhoudLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vormLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vormComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vormButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inhoudLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inhoudField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totaleInhoudLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totaleInhoudField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lijstOpslaanButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lijstOpslaanButton.setText("Lijst Opslaan");
        lijstOpslaanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lijstOpslaanButtonActionPerformed(evt);
            }
        });

        lijstLadenButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lijstLadenButton.setText("Lijst Laden");
        lijstLadenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lijstLadenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lijstOpslaanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(lijstLadenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lijstOpslaanButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lijstLadenButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        jPanel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        vormLijst.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        vormLijst.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        vormLijst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                vormLijstMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(vormLijst);

        verwijderVormButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        verwijderVormButton.setText("Verwijder Vorm");
        verwijderVormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verwijderVormButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(verwijderVormButton, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verwijderVormButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vormButtonActionPerformed
        new VormFrame(this, vormControle, (String) vormComboBox.getSelectedItem());
    }//GEN-LAST:event_vormButtonActionPerformed

    private void vormLijstMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vormLijstMouseReleased
        int index = vormLijst.getSelectedIndex();
        if (index > -1) {
            verwijderVormButton.setEnabled(true);
            inhoudField.setText(String.valueOf(vormControle.getVorm(index).getInhoud()));
        } else {
            verwijderVormButton.setEnabled(false);
        }
    }//GEN-LAST:event_vormLijstMouseReleased

    private void verwijderVormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verwijderVormButtonActionPerformed
        int index = vormLijst.getSelectedIndex();
        if (index > -1) {
            vormControle.verwijderVorm(index);
            verversScherm();
            inhoudField.setText("");
        } else {
            showMessage("Er is geen item geselecteerd.", "Foutmelding");
        }
        verwijderVormButton.setEnabled(false);
    }//GEN-LAST:event_verwijderVormButtonActionPerformed

    private void lijstOpslaanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lijstOpslaanButtonActionPerformed
        if (vormControle.slaVormVerzamelingOp()) {
            showMessage("Verzameling is succesvol opgeslagen!", "Succes");
        }
    }//GEN-LAST:event_lijstOpslaanButtonActionPerformed

    private void lijstLadenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lijstLadenButtonActionPerformed
         if (vormControle.laadVormVerzameling()) {
             showMessage("Verzameling is succesvol geladen!", "Succes");
             verversScherm();
         }
    }//GEN-LAST:event_lijstLadenButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inhoudField;
    private javax.swing.JLabel inhoudLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton lijstLadenButton;
    private javax.swing.JButton lijstOpslaanButton;
    private javax.swing.JTextField totaleInhoudField;
    private javax.swing.JLabel totaleInhoudLabel;
    private javax.swing.JButton verwijderVormButton;
    private javax.swing.JButton vormButton;
    private javax.swing.JComboBox vormComboBox;
    private javax.swing.JLabel vormLabel;
    private javax.swing.JList vormLijst;
    // End of variables declaration//GEN-END:variables
}
