(function(m){var window=this;var qC=function(a){if(!a.length)return 0;var b=a[0],c=b.offsetHeight;1<a.length&&(c=a[1].offsetTop-b.offsetTop);return c};var rC=function(a){var b=(0,m.Ky)("/api/lounge/screens");(0,m.W)(b,{method:"GET",O:a,withCredentials:!0,onSuccess:function(a,b){this.vf=(0,m.Fg)((0,m.Lk)(b),function(a){return new m.Zv(a)});this.log_("Load account screens successfully.");this.zl();this.Yi();this.K("accountScreenLoad")},onError:function(){(0,m.py)(m.hC,"RM","Load account screens failed.")}})};
var sC=function(){var a=m.ge.getInstance(),b=tC;if(!b)return[];a=(0,m.J)((0,m.N)(a,"scroll-unit"),b);if(0>=a.length)return[];var c=b.scrollTop,d=qC(a),e=b.offsetHeight,b=Math.max(Math.floor(c/d),0),c=Math.min(Math.ceil((c+e)/d),a.length);return(0,m.Ha)((0,m.Ga)(a),b,c)};var uC=function(a,b){var c=(0,m.I)(b);if(c){var d=(0,m.N)(a,"toggled"),c=(0,m.J)(d,c);(0,m.C)(c,function(a){(0,m.H)(a,d)})}};
var vC=function(a){var b=(0,m.Q)("related-video",a),b={video_id:(0,m.F)(b,"video-id"),action_dismiss_video_recommendation:1},b=(0,m.Pb)("/related_ajax",b);window.spf.load(b,{method:"POST",onSuccess:function(){m.P.hide(a)}})};
var wC=function(a){var b=a.currentTarget.href,c=(0,m.We)();if(c){var d=(0,m.Rn)(b).v;if((0,m.w)("VIDEO_ID")==d){c=Math.floor(c.getCurrentTime());a=a.currentTarget;var c={t:c},d=b.split("#",2),b=d[0],d=1<d.length?"#"+d[1]:"",e=(0,m.Ul)(d),g;for(g in c)e[g]=c[g];(0,m.Mm)(e)||(d=(0,m.Im)("#",e));a.href=b+d}}};var xC=function(a){a.stopPropagation();a=a.currentTarget;var b=(0,m.L)(a,"video-list-item");if(b)switch((0,m.F)(a,"action")){case "hide":vC(b)}};
var yC=function(){var a=m.Me?(0,m.Q)("playlist-videos-list"):tC,b=(0,m.Q)(zC,a);if(b){var c=m.ge.getInstance();if(a&&b){var d=(0,m.J)((0,m.N)(c,"scroll-unit"),a),b=(0,m.Ca)(d,b);if(0<=b&&a&&!((0,window.isNaN)(b)||0>b)&&(c=(0,m.J)((0,m.N)(c,"scroll-unit"),a),!(0>=c.length))){b>=c.length&&(b=c.length-1);var d=qC(c),e=a.offsetHeight,g=Math.max(Math.floor(a.scrollTop/d),0);b>g-1&&(d=Math.floor(e/d),e=c.length,b+d>e&&(b=e-d+1));0>b&&(b=0);b=c[b].offsetTop;a&&!(0,window.isNaN)(b)&&(0>b&&(b=0),a.scrollTop=
b,(0,m.qb)(a,"scroller-offset",b+""),(0,m.Kj)(a))}}}};var AC=function(a,b){var c=null;(0,m.C)(a,function(a){(0,m.nc)(a,zC)&&(c=a)});if(c){var d=(0,m.tl)(c);d||(d=a[0]);var e=(0,m.sl)(c);e||(e=a[a.length-1]);var g=m.Je,h=BC;g&&d&&(d={v:(0,m.F)(d,"video-id")},b?d.shuffle=b:-1!=g.href.indexOf("shuffle=")&&(d.shuffle=0),g.href=(0,m.ul)(g.href,d));h&&e&&(d={v:(0,m.F)(e,"video-id")},b?d.shuffle=b:-1!=h.href.indexOf("shuffle=")&&(d.shuffle=0),h.href=(0,m.ul)(h.href,d))}};
var CC=function(a){var b=(0,m.w)("SHUFFLE_VALUE");if(!b){var c=0;(0,m.C)(a,function(a){(0,m.nc)(a,zC)&&(c=(0,m.F)(a,"index"))});b=(c<<8)+Math.floor(256*Math.random());(0,m.Ma)("SHUFFLE_VALUE",b)}return b};var DC=function(a){(0,m.vl)(a,function(a,c){var d=(0,window.parseInt)((0,m.F)(a,"index"),10),e=(0,window.parseInt)((0,m.F)(c,"index"),10);return d-e});return a};
var EC=function(a,b){function c(a){var c=0,d=[];for(a=a.split("");a.length;){var c=(b+c)%a.length,e=a[c];(0,m.Ea)(a,c);d.push(e)}return d.join("")}(0,m.vl)(a,function(a,b){var d=(0,m.F)(a,"video-id"),e=(0,m.F)(b,"video-id");return c(d).localeCompare(c(e))});var d=b>>8,e=(0,m.Aa)(a,function(a){a=(0,m.F)(a,"index");return d==a})||0;0<e&&(a=(0,m.Ha)(a,e).concat((0,m.Ha)(a,0,e)));return a};var FC=function(a,b){(0,m.vk)((0,m.Wb)({lact:a,event:"interstitialtimeout",delay:b}))};
var GC=function(a,b){var c={lact:a,event:"interstitialclick",delay:(0,m.O)()-b};(0,m.vk)((0,m.Wb)(c));m.P.hide(HC);(0,m.V)((0,m.I)("player"),"off-screen-trigger");IC&&(0,m.y)(IC);(0,m.Fe)("interstitial",!1)};var JC=function(a,b,c){var d=a.currentTarget.href;b=b||"BFa";var e={},g=(0,m.w)("SHUFFLE_VALUE");g?e.shuffle=g:-1!=d.indexOf("shuffle=")&&(e.shuffle=0);e&&(d=(0,m.ul)(d,e));a.currentTarget.href=d;(0,m.Ke)(d,b,c)};var KC=function(){(0,m.E)("watch-list-change")};
var LC=function(a){if("NEAR_END"==a.slice(0,-1)&&(a=(0,window.parseInt)(a.slice(-1),10),m.Me||((0,m.Ne)(),(0,m.Qe)(a)),5==a&&(0,m.w)("PREFETCH_NEXT_PLAYLIST_VIDEO")&&(0,m.Ge)()&&!m.He)){a=m.Ie;var b;a&&(b=(0,m.F)(a,"autoplay-clicktracking")||"");a=m.Je.href;(0,m.Ke)(a,"bf_next",b,!0);b=window.ytspf||{};window.spf&&b.enabled&&a&&window.spf.prefetch(a)}};var MC=function(){var a=sC();(0,m.C)(a,function(a){(0,m.gl)(a)})};var NC=function(){var a=(0,m.J)("related-video-featured");(0,m.C)(a,function(a){m.P.show(a)})};
var OC=function(a){if(a.source==window&&a.data&&"CastApi"==a.data.source&&"Hello"==a.data.event)for(;PC.length;)PC.shift()()};var QC=function(){m.He=!0};var RC=function(){var a=BC;(0,m.Ke)(a.href,"keys");(0,m.ac)(a.href)};var SC=function(){(0,m.Fe)("keys")};var TC=function(a){switch(a){case 5:(0,m.Le)(5,"html5_ns")}};
var UC=function(a){if(0==a){var b;(0,m.w)("PLAYLIST_INTERSTITIAL")&&(0,m.Ge)()?(b=(0,m.Ee)()/6E4,b=Math.min(0.005,8.34522E-4*Math.exp(0.100073*b)),b=Math.random()<b):b=!1;b?(m.P.show(HC),(0,m.R)((0,m.I)("player"),"off-screen-trigger"),(0,m.T)(VC),b=(0,m.Ee)(),VC=(0,m.M)(HC,"click",(0,m.s)(GC,b,(0,m.O)())),IC=(0,m.x)((0,m.s)(FC,b,18E4),18E4),(0,m.vk)((0,m.Wb)({lact:b,event:"interstitialshown"}))):(0,m.Fe)("autoplay",!0)}m.Te&&(2==a?(0,m.G)(m.Ve,"paused"):1==a&&(0,m.H)(m.Ve,"paused"))};
var WC=function(a){var b=m.Ie,c=(0,m.Ic)(a.currentTarget,"li");if(b&&c){var d=tC;(0,m.G)(d,"playlist-editing-locked");a=(0,m.F)(b,"full-list-id");var b=(0,m.F)(c,"video-id"),e=(0,m.F)(c,"index");(0,m.W)("/addto_ajax?action_delete_from_playlist=1",{format:"XML",method:"POST",ba:{video_ids:b,session_token:(0,m.Vl)("addto_ajax")||"",full_list_id:a,index:e-1},onSuccess:function(){(0,m.Cc)(c);var a=(0,m.vc)("li",null,d),b=1,e=0;(0,m.C)(a,function(a){if(!m.Me)if((0,m.nc)(a,zC))e=b;else{var c=(0,m.vc)("span",
"count",a);c&&c[0]&&(c[0].innerHTML=b)}(0,m.qb)(a,"index",b);b+=1});m.Me||((0,m.I)("watch7-playlist-current-index").innerHTML=e,(0,m.I)("watch7-playlist-length").innerHTML=b-1);AC(a,(0,m.w)("SHUFFLE_VALUE"))},Ca:function(){(0,m.H)(d,"playlist-editing-locked");KC()}})}};var XC=function(a,b){var c=(0,m.F)(a.currentTarget,"clicktracking")||"";JC(a,b,c)};var YC=function(a){var b=(0,m.Ic)(a.currentTarget,"li"),b=(0,m.F)(b,"clicktracking")||"";JC(a,void 0,b)};
var ZC=function(){if(m.Me){var a=(0,m.Dd)(m.Cd.getInstance(),$C);(0,m.pc)(m.Ve,"watch-playlist-collapsed",a)}else(0,m.qc)((0,m.I)("player"),"watch-playlist-collapsed")||(a=(0,m.Nl)((0,m.I)("watch7-playlist-tray-container")),(0,m.x)(MC,a))};
var aD=function(){var a=tC,b=(0,m.Ga)(a.getElementsByTagName("li"));if((0,m.Dd)(m.Cd.getInstance(),bD))b=DC(b),(0,m.Ma)("SHUFFLE_VALUE",0);else var c=CC(b),b=EC(b,c);(0,m.Bc)(a);(0,m.C)(b,function(b){a.appendChild(b)});c=(0,m.w)("SHUFFLE_VALUE");AC(b,c);yC();MC();KC()};var cD=function(){var a=(0,m.w)("PLAYER_REFERENCE");a&&a.getPlayerState?1==a.getPlayerState()?a.pauseVideo():a.playVideo():((0,m.qc)(m.Ve,"paused"),m.Oe=!m.Oe)};
var dD=function(){var a=(0,m.Ge)(),b=m.jd.getInstance();(0,m.mk)(76,a);b.save();(0,m.Ma)("LIST_AUTO_PLAY_ON",!a)};var eD=function(){var a=m.Ie;return!(!a||"False"==(0,m.F)(a,"shareable"))};var fD=function(a){var b=(0,m.w)("LIST_END_TIME");b||(b=a.getDuration());for(var c=5;0<c;c--)a.addCueRange("NEAR_END"+c,b-c,b-c+1);a.addEventListener("onCueRangeEnter",LC)};
var gD=function(a){if(!a.metaKey&&!a.ctrlKey){var b=a.target;if("INPUT"!=b.tagName&&"TEXTAREA"!=b.tagName&&"SELECT"!=b.tagName&&"EMBED"!=b.tagName)switch(a.keyCode){case 78:a.shiftKey&&(0,m.E)("player-shortcut-next");break;case 80:a.shiftKey&&(0,m.E)("player-shortcut-prev");break;case 106:(0,m.E)("player-shortcut-rewind");break;case 108:(0,m.E)("player-shortcut-fast-forward");break;case 107:(0,m.E)("player-shortcut-play-pause")}}};
var hD=function(a){var b=window.location.href;b.indexOf("#")==b.length-1&&m.Mc&&(window.location.hash="#!");var b=window.document.body,c=(0,m.ki)(b),d=[];d.push("<!DOCTYPE html>");d.push("<html><head>",a,"</head><body>","","</body></html>");a=(0,m.ev)(c,"display: none");b.appendChild(a);b=d.join("");d=a.contentDocument||a.contentWindow.document;d.open();d.write(b);d.close();m.az=a};
var iD=function(){var a=(0,m.J)("related-video-featured");2==a.length?(0,m.uc)(a[0],"related-video-featured-booster")?m.P.show(a[1]):m.P.show(a[0]):(0,m.C)(a,function(a){m.P.show(a)})};var jD=function(a){0==a.length?NC():(0,m.bz)("watch_related",a[0],null,function(a,c){var d=c.html_content||"",e=(0,m.I)(window.pyv_related_box_id||"watch-related");e&&(0!=e.innerHTML.indexOf(d)&&e.insertBefore((0,m.Sl)(d),e.firstChild),(d=(0,m.I)("pyv-watch-related-dest-url"))&&d.setAttribute("href",m.cz),(0,m.gz)())})};
var kD=function(a){var b=(0,m.Pb)("/related_ajax",{video_id:(0,m.w)("VIDEO_ID"),action_more_related_videos:1});window.spf.load(b,{onSuccess:a})};var lD=function(a){if("true"==(0,m.F)(a,"loaded"))return null;(0,m.qb)(a,"loaded","true");return(0,m.W)("/watch_ajax",{format:"XML",da:{action_get_video_attributions_component:1,v:(0,m.w)("VIDEO_ID")},onSuccess:function(b,c){a.innerHTML=c.html_content}})};
var mD=function(a){return(0,m.W)("/insight_ajax",{format:"XML",method:"POST",da:{action_get_statistics_and_data:1,v:(0,m.w)("VIDEO_ID")},ba:{session_token:(0,m.Vl)("insight_ajax")},onSuccess:function(b,c){a(c.html_content,c.graph_data,!0)},onError:function(){a(null,null,!1)}})};
var nD=function(a){var b=0,c=(0,m.We)();c&&c.pauseVideo&&(c.pauseVideo(),b=c.getCurrentTime());b=Math.floor(b);c=Math.floor(b/60);return(0,m.W)("/watch_ajax",{method:"GET",da:{action_get_report_video_component:1,video_id:(0,m.w)("VIDEO_ID"),t_mins:c,t_secs:b-60*c},onSuccess:function(b,c){a(c.report_html,!0)},onError:function(){a(null,!1)}})};var oD=function(){var a=null;if(eD()){var b=(0,m.I)("share-with-playlist");if(!b||b&&b.checked)a=(a=m.Ie)?(0,m.F)(a,"full-list-id"):""}return a};
var pD=function(){var a=(0,m.Q)("yt-uix-button-toggled",(0,m.I)("action-panel-share"));return eD()&&a?(0,m.F)(a,"video-id"):(0,m.w)("VIDEO_ID")};
var qD=function(){(0,m.nc)(window.document.body,"site-center-aligned")?(m.Me=!0,m.Ve=(0,m.I)("watch-appbar-playlist"),tC=(0,m.Q)("playlist-videos-list",m.Ve),m.Re=(0,m.Q)("toggle-autoplay",m.Ve),bD=(0,m.Q)("shuffle-playlist",m.Ve),$C=(0,m.Q)("toggle-menu-visibility",m.Ve),m.Je=(0,m.Q)("next-playlist-list-item",m.Ve),BC=(0,m.Q)("prev-playlist-list-item",m.Ve),m.Ie=(0,m.Q)("playlist-info",m.Ve),zC="currently-playing"):(m.Me=!1,m.Ve=(0,m.I)("playlist"),tC=(0,m.I)("watch7-playlist-tray"),m.Re=(0,m.I)("watch7-playlist-bar-autoplay-button"),
bD=(0,m.I)("watch7-playlist-bar-shuffle-button"),$C=(0,m.I)("watch7-playlist-bar-toggle-button"),m.Je=(0,m.I)("watch7-playlist-bar-next-button"),BC=(0,m.I)("watch7-playlist-bar-prev-button"),m.Ie=(0,m.I)("watch7-playlist-data"),HC=(0,m.I)("watch7-playlist-interstitial"),zC="playlist-bar-item-playing");if(m.Ve&&tC){m.Me||(rD.push((0,m.M)((0,m.I)("watch7-playlist-scrollfloater-autoplay-toggle"),"click",cD)),m.Ue=m.P.uj((0,m.I)("watch7-content")).y,sD.push((0,m.B)("page-scroll",m.Se)));var a=(0,m.We)();
a&&a.addEventListener("onReady",fD);rD.push((0,m.M)(m.Re,"click",dD));rD.push((0,m.M)(bD,"click",aD));rD.push((0,m.M)($C,"click",ZC));rD.push((0,m.M)(m.Je,"click",function(a){XC(a,"bf_next")}));rD.push((0,m.M)(BC,"click",function(a){XC(a,"bf_prev")}));rD.push((0,m.Am)(tC,"click",YC,"a"));rD.push((0,m.X)(tC,"click",WC,"yt-uix-button-playlist-remove-item"));sD.push((0,m.B)("navigate",QC));sD.push((0,m.B)("player-state-change",UC));sD.push((0,m.B)("player-error",TC));sD.push((0,m.B)("player-shortcut-next",
SC));sD.push((0,m.B)("player-shortcut-prev",RC));(0,m.w)("SKIP_TO_NEXT_VIDEO")&&(0,m.Le)(5);yC();MC();KC()}};
m.tD=function(a,b){var c=a.type;if((0,m.ga)(c))switch(c.toLowerCase()){case "checkbox":case "radio":a.checked=b?"checked":null;break;case "select-one":a.selectedIndex=-1;if((0,m.q)(b))for(var d=0;c=a.options[d];d++)if(c.value==b){c.selected=!0;break}break;case "select-multiple":c=b;(0,m.q)(c)&&(c=[c]);for(var e=0;d=a.options[e];e++)if(d.selected=!1,c)for(var g,h=0;g=c[h];h++)d.value==g&&(d.selected=!0);break;default:a.value=null!=b?b:""}};
var uD=function(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var g=arguments[e];if(c>=g.length)return b;d.push(g[c])}b.push(d)}};var vD=function(){this.g=new m.Lv(this);this.i=!1};
var wD=function(){if((0,m.w)("WATCH_LEGAL_TEXT_ENABLE_AUTOSCROLL")){var a=window.document.getElementById("watch_companion_legal_text");a&&(xD=new vD,xD.start(a))}var b=(0,m.w)("ADS_DATA");if(b){yD(b);zD=b;AD=(0,m.We)();null!=AD&&(AD.addEventListener("onApiChange",BD),AD.addEventListener("onReady",CD));(0,m.w)("WATCH_RELATED_DELAY")||DD();b.use_gut&&(window.spf.scripts.unload("//www.googletagservices.com/tag/js/gpt.js"),(0,m.tb)("//www.googletagservices.com/tag/js/gpt.js",function(){ED(b.gut_vars.tag)}));
if(b.show_afv||b.show_afc)window.spf.scripts.unload("//pagead2.googlesyndication.com/pagead/show_companion_ad.js"),(0,m.tb)("//pagead2.googlesyndication.com/pagead/show_companion_ad.js"),(0,m.tb)("//www.google.com/jsapi?autoload=%7B%22modules%22%3A%5B%7B%22name%22%3A%22ads%22%2C%22version%22%3A%221%22%2C%22callback%22%3A%22(function()%7B%7D)%22%2C%22packages%22%3A%5B%22content%22%5D%7D%5D%7D");b.show_afc&&FD(b);GD();b.check_status&&HD()}};
var DD=function(){var a=(0,m.w)("ADS_DATA");a&&(a.show_pyv?ID(a):NC())};var HD=function(){function a(){JD=!0;"google_ad_status"in window?(0,m.vk)("adstat=s"):(0,m.vk)("adstat=l")}(0,m.tb)("//static.doubleclick.net/instream/ad_status.js",a);(0,m.x)(function(){JD||"google_ad_status"in window||(window.spf.scripts.ignore("//static.doubleclick.net/instream/ad_status.js",a),(0,m.vk)("adstat=f"))},5E3)};
var GD=function(){KD&&null!=AD&&null!=AD.getOptions&&(0,m.sk)(AD.getOptions())&&(0,m.Ba)(AD.getOptions(),"ad")&&AD.getOption("ad","PAGE_JAVASCRIPT_INITIALIZED",{})};var yD=function(a){LD=[];if("afv_vars"in a)for(var b in a.afv_vars)window[b]=a.afv_vars[b],LD.push(b)};
var ED=function(a){"googletag"in window&&(MD=window.googletag.defineSlot(a,[[300,250],[300,60]],"yt-gut-content"))&&(MD.set("ad_type","flash"),MD.addService(window.googletag.companionAds()),window.googletag.enableServices(),a=MD.getSizes(),ND=a[0],OD=a[1])};var PD=function(a,b){a||(a="");b||(b=!1);var c=(0,m.I)("watch-channel-brand-div");c&&(0,m.Gm)(c,"collapsible",b);if(c=(0,m.I)("google_companion_ad_div"))c.innerHTML=a;QD()};
var RD=function(a,b){var c=Math.round(1E4*Math.random());return['<iframe src="',a,'" name="ifr_300x',b,"ad",c,'" id="ifr_300x',b,"ad",c,'" width="300" height="',b,'" marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>'].join("")};var SD=function(a){return!!a.match("/subscribe_widget.*render=video_wall_companion")};var TD=function(a){a=a.replace(";dc_seed=",";kmyd=watch-channel-brand-div;dc_seed=");var b=RD(a,250);a=SD(a);PD(b,a)};
var UD=function(a){a=a.replace(";dc_seed=",";kmyd=watch-longform-ad;dc_seed=");var b=RD(a,60);a=SD(a);PD(b,a)};
var VD=function(a,b){var c=250;"video"==a&&(c=60);var d=(0,window.decodeURIComponent)(b);PD(['<iframe name="fw_ad" id="fw_ad" ','width="300" height="'+c+'" ','marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>'].join(""));var e=(0,m.I)("fw_ad");if(e){var e=e.contentWindow?e.contentWindow:e.contentDocument.document?e.contentDocument.document:e.contentDocument,g=window.navigator.userAgent.toLowerCase(),c=-1!=g.indexOf("msie"),g=-1!=g.indexOf("opera");e.document.open();
e.document.write(d);c||g?(0,m.x)(function(){e.document.close()},7500):e.document.close()}};var QD=function(){(0,m.E)("watchads-adLoad")};var WD=function(){window.google_ad_output="html";window.google_ad_height="250";window.google_ad_format="300x250_as";window.google_container_id="google_companion_ad_div"};
var XD=function(){var a=window.document.getElementById("google_companion_ad_div");if(a&&(a=a.firstElementChild))try{a.contentWindow.postMessage((0,window.encodeURIComponent)(YD)+","+(0,window.encodeURIComponent)(ZD),"*")}catch(b){}};var $D=function(){var a=window.document.getElementById("movie_player");a&&a.pauseVideo()};var aE=function(){};var bE=function(){QD()};
var ID=function(a){hD("<script>var pyvOptions = "+a.pyv_vars.iframe_json+'; for (var key in pyvOptions) { window[key] = pyvOptions[key]; } window["google_ad_request_done"] = parent.yt.www.ads.pyv.pyvWatchAfcWithPpvCallback; \x3c/script><script src="//pagead2.googlesyndication.com/pagead/show_ads.js">\x3c/script>');a.log_pyv&&(0,m.x)(function(){"google_render_ad"in window?(0,m.vk)("pyvls"):(0,m.vk)("pyvlf")},5E3)};
var FD=function(a){if(!cE){if(!a){if(!zD)return;a=zD}var b=(0,m.n)("google.ads.Ad");b?(cE=!0,new b(a.afv_vars.google_ad_client,"google_companion_ad_div",a.afc_vars)):dE=(0,m.x)(function(){FD(a)},200)}};var BD=function(){GD()};var CD=function(){KD=!0;GD()};var eE=function(){var a=(0,m.w)("BG_I",null),b=(0,m.w)("BG_IU",null),c=(0,m.w)("BG_P");b?(0,m.tb)(b,function(){fE=new window.botguard.bg(c)}):a&&(eval(a),fE=new window.botguard.bg(c))};
var gE=function(){var a=(0,m.bq)();m.P.hide((0,m.Q)("flag-comment-step1",a));m.P.show((0,m.Q)("flag-comment-step2",a));m.P.hide((0,m.Q)("flag-comment-step3",a))};
var hE=function(){var a=(0,m.bq)(),b=(0,m.Q)("flag-comment-form",a),c=(0,m.Q)("flag-comment-block-user-input",a),d=(0,m.Q)("submit-flag-comment",a),e=(0,m.Q)("flag-comment-error-msg",a);m.P.hide(e);c.disabled=!0;d.disabled=!0;(0,m.W)("/comment_servlet",{format:"XML",method:"POST",da:{flag_comment:1},ba:(0,m.cl)((0,m.Dm)(b)),onSuccess:function(b,c){c&&c.html_content?(m.P.hide((0,m.Q)("flag-comment-step1",a)),m.P.hide((0,m.Q)("flag-comment-step2",a)),m.P.show((0,m.Q)("flag-comment-step3",a)),(0,m.Q)("flag-comment-captcha-placeholder",
a).innerHTML=c.html_content):m.Xp.getInstance().hide()},onError:function(a,b){var k=b&&b.error_message;if(k){var p=(0,m.Q)("yt-alert-message",e);(0,m.ak)(p,k)}m.P.show(e);c.disabled=!1;d.disabled=!1}})};var iE=function(a){var b=(0,m.bq)(),c=(0,m.Q)("abuse-type-placeholder",b);a=(0,m.Ic)(a.currentTarget,"LABEL");(0,m.ak)(c,(0,m.Yj)(a));(0,m.Q)("continue-flag-comment",b).disabled=!1};
var jE=function(a){var b;switch(a){case "PENDING":b=(0,m.A)("COMMENT_PENDING");break;case "BLOCKED":b=(0,m.A)("COMMENT_BLOCKED");break;case "EMAIL":b=(0,m.A)("COMMENT_ERROR_EMAIL");break;case "INLINE_CAPTCHAFAIL":b=(0,m.A)("COMMENT_CAPTCHAFAIL");break;case "SHOW_COUNTDOWN":b=(0,m.A)("SHOW_COUNTDOWN");break;case "FAILED_MAINTENANCE":b=(0,m.A)("COMMENT_FAILED_MAINTENANCE");break;case "FAILED_OWNER_LINKING":b=(0,m.A)("COMMENT_OWNER_LINKING");break;case "FAILED_HASLINK":b=(0,m.A)("FAILED_HASLINK");break;
case "FAILED_HASTAGS":b=(0,m.A)("FAILED_HASTAGS");break;case "FAILED_ASCIIART":b=(0,m.A)("FAILED_ASCIIART");break;case "FAILED_TOOSHORT":b=(0,m.A)("FAILED_TOOSHORT");break;case "FAILED_TOOLONG":b=(0,m.A)("FAILED_TOOLONG");break;case "FAILED_BADPARENT":b=(0,m.A)("FAILED_BADPARENT")}return b||null};
var kE=function(a,b,c){this.B=!!c;this.Za=a;this.Dr=(0,m.I)("all-comments");this.jf=(0,m.Cj)("button","post-button",a);this.Ic=(0,m.Cj)("textarea",null,a);this.$f=null;this.b=(0,m.Q)("comments-remaining",this.Za);this.A=(0,window.parseInt)((0,m.F)(this.b,"max-count"),10);this.Yf=(0,m.Q)("comments-post-message",this.Za);this.Cr=(0,m.Q)("yt-alert-content",this.Yf);this.g=(0,m.Q)("comments-threshold-countdown",this.Za);this.k=[];this.j=[];this.i=null;this.Vy=!!(0,m.w)("COMMENTS_IS_LIVE_EVENT");lE(this);
mE(this,this.Ic,"focus",this.Ur);mE(this,this.Ic,"blur",this.Sz);mE(this,this.Za,"submit",this.Sr);mE(this,this.Ic,"change",this.Tr);mE(this,this.Ic,"keyup",this.Tr);mE(this,this.Ic,"keydown",this.Tz);b&&this.Ur()};var mE=function(a,b,c,d){a.k.push((0,m.M)(b,c,(0,m.r)(d,a)))};var nE=function(a){a.$f&&(a.$f.innerHTML="")};var lE=function(a){var b=a.A-a.Ic.value.length;a.b.innerHTML=(0,m.$n)("CHARACTERS_REMAINING",b);b=0>b;(0,m.Gm)(a.b,"too-many",b);a.jf.disabled=b};
var oE=function(a,b){var c=(0,m.r)(function(){0==b?((0,m.ao)(d),pE(this)):(b--,this.g.innerHTML=(0,m.$n)("SECONDS_REMAINING",b))},a);qE(a);var d=(0,m.bo)(c,1E3);c();a.j.push(d)};var qE=function(a){m.P.hide(a.b);m.P.show(a.g);a.jf.disabled=!0};var pE=function(a){m.P.hide(a.g);m.P.hide(a.Yf);m.P.show(a.b);a.g.innerHTML="";a.jf.disabled=!1};
var rE=function(a,b,c){var d=jE(b)||(0,m.A)("COMMENT_ERROR");a.Cr.innerHTML=d;(0,m.Ln)(a.Yf,"yt-alert-info","yt-alert-error");m.P.show(a.Yf);switch(b){case "INLINE_CAPTCHA":case "INLINE_CAPTCHAFAIL":(0,m.W)("/comment_servlet?gimme_captcha=1",{format:"XML",method:"POST",ba:{session_token:(0,m.Vl)("comment_servlet")},onSuccess:function(a,b){this.$f||(this.$f=window.document.createElement("div"),this.$f.className="comment-captcha",(0,m.Hn)(this.$f,this.Ic));this.$f.innerHTML=b.html_content;this.jf.disabled=
!1},O:a});break;case "SHOW_COUNTDOWN":oE(a,(0,window.parseInt)(c.countdown_timer,10)||30);break;default:a.jf.disabled=!1,nE(a)}};var sE=function(a){this.aa=a;this.Ss=(0,m.Q)("yt-uix-pager-show-more");this.i=!!(0,m.w)("ENABLE_LIVE_COMMENTS");this.b=[];(a=(0,m.Q)("comments-pagination",this.aa))&&(0,m.F)(a,"ajax-enabled")&&this.b.push((0,m.X)(this.aa,"click",(0,m.r)(this.j,this),"yt-uix-pager-button"))};
var tE=function(a,b){var c=(0,m.vc)("li","comment",void 0),c=(0,m.F)(c[c.length-1],"id"),d=a.pj?!1:!0;m.P.show("comments-loading");uE(a,c,function(a,c){c.html_content&&(m.P.hide("comments-loading"),this.pj=window.document.createElement("div"),this.pj.innerHTML=c.html_content,!d&&0<(0,m.vc)("li","comment",this.pj).length&&m.P.show(this.Ss),b&&b())})};
var uE=function(a,b,c){(0,m.W)("/watch_ajax?action_get_comments=1",{format:"XML",da:{v:(0,m.w)("VIDEO_ID"),p:1,commentthreshold:(0,m.w)("COMMENTS_THRESHHOLD"),commenttype:"everything",enable_live_comments:a.i?"yes":null,last_comment_id:b,page_size:(0,m.w)("COMMENTS_PAGE_SIZE"),source:(0,m.w)("COMMENT_SOURCE")},onSuccess:c,O:a})};var vE=function(a,b,c){a=(0,m.Ic)(a,"form");(0,m.Un)(a,"initialized")||((0,m.qb)(a,"initialized","true"),wE=new kE(a,!b,c),b&&wE.focus())};
var xE=function(a){a=a.currentTarget;var b=(0,m.Ic)(a,null,"comment");switch((0,m.F)(a,"action")){case "approve":yE(b);break;case "block":(0,window.confirm)((0,m.A)("BLOCK_USER"))&&(zE(b,!0),(0,m.R)(b,"blocked"));break;case "unblock":zE(b,!1);(0,m.V)(b,"blocked");break;case "flag-in-place":if(AE(!1)){var c=(0,m.I)("comment-flag-area");a=(0,m.F)(b,"id");var d=(0,m.F)(b,"author-id"),e=(0,m.Yj)((0,m.Q)("author",b)),b=(0,m.Q)("comment-text",b).innerHTML,g=(0,m.w)("VIDEO_ID");m.Xp.getInstance().show(c);
c=(0,m.bq)();(0,m.Q)("flagged-comment-id",c).value=a;(0,m.Q)("flagged-comment-author-id",c).value=d;(0,m.Q)("flagged-comment-video-id",c).value=g;(0,m.ak)((0,m.Q)("flagged-comment-author-name",c),e);(0,m.Q)("flagged-comment-text",c).appendChild((0,m.Sl)(b));(0,m.M)((0,m.Q)("continue-flag-comment",c),"click",gE);(0,m.X)(c,"click",hE,"submit-flag-comment");(0,m.X)(c,"click",iE,"abuse-type-radio-input")}break;case "flag":BE(b,"mark_comment_as_spam");break;case "flag-profile-pic":BE(b,"flag_profile_pic");
break;case "unflag":a=(0,m.F)(b,"id");(0,m.W)("/comment_servlet",{format:"XML",method:"POST",ba:{unmark_comment_as_spam:a,entity_id:(0,m.w)("VIDEO_ID"),session_token:(0,m.Vl)("comment_servlet")}});break;case "hide":(0,m.R)(b,"hidden");break;case "show":(0,m.V)(b,"hidden");break;case "remove":CE(b);break;case "reply":DE(b);break;case "realtime-reply":AE(!0)&&(wE||(a=(0,m.Q)("comments-textarea",(0,m.I)("comments-view")),vE(a)),a=wE,a.reset(),a.focus());break;case "vote-up":EE(b,!0);break;case "vote-down":EE(b,
!1);break;case "show-parent":FE(b)}};var AE=function(a){return(0,m.w)("COMMENTS_SIGNIN_URL")?((0,m.$b)((0,m.w)("COMMENTS_SIGNIN_URL")),!1):a&&(0,m.w)("COMMENTS_CHANNEL_CREATE_URL")?((0,m.$b)((0,m.w)("COMMENTS_CHANNEL_CREATE_URL")),!1):(0,m.w)("COMMENTS_YPC_CAN_POST_OR_REACT_TO_COMMENT")?!0:!1};
var yE=function(a){var b=(0,m.F)(a,"id"),c=(0,m.w)("VIDEO_ID");(0,m.V)(a,"pending");(0,m.W)("/comment_servlet?field_approve_comment=1",{format:"XML",method:"POST",ba:{comment_id:b,entity_id:c,session_token:(0,m.Vl)("comment_servlet")},onError:function(){(0,m.R)(a,"pending")}})};
var zE=function(a,b){var c={};c["action_"+(b?"":"un")+"block_commenter"]=1;var d=(0,m.F)(a,"id");(0,m.W)("/link_ajax",{format:"XML",method:"POST",da:c,ba:{session_token:(0,m.Vl)("link_ajax"),comment_id:d},onSuccess:function(a,b){b&&b.success_message&&window.alert(b.success_message)},onError:function(a,b){b&&b.error_message&&window.alert(b.error_message)}})};
var BE=function(a,b){if(AE(!1)){var c=(0,m.F)(a,"id"),d=(0,m.w)("VIDEO_ID");m.P.hide(a);(0,m.R)(a,"flagged");d={entity_id:d};d[b]=c;(0,m.W)("/comment_servlet",{format:"XML",method:"POST",da:d,ba:{session_token:(0,m.Vl)("comment_servlet")},onError:function(){m.P.show(a);(0,m.V)(a,"flagged")}})}};
var CE=function(a){var b=(0,m.F)(a,"id"),c=(0,m.w)("VIDEO_ID");m.P.hide(a);(0,m.W)("/comment_servlet?remove_comment=1",{format:"XML",method:"POST",ba:{comment_id:b,entity_id:c,session_token:(0,m.Vl)("comment_servlet")},onError:function(){m.P.show(a)}})};
var DE=function(a){if(AE(!0))if((0,m.uc)(a,"replying"))(0,m.uc)(a,"replying")&&((0,m.V)(a,"replying"),a=(0,m.Q)("comments-post-container",a),(0,m.Cc)(a));else{(0,m.R)(a,"replying");var b=(0,m.Q)("comments-post",(0,m.I)("watch-discussion")||(0,m.I)("watch-discussion")),b=(0,m.sn)(b),c=window.document.createElement("div");c.className="comments-post-container";a.appendChild(c);c.appendChild(b);b=new kE(b);b.reset();c=(0,m.F)(a,"id");b.Za.reply_parent_id.value=c;if(a=(0,m.F)(a,"tag"))b.i=a;b.focus()}};
var EE=function(a,b){if(AE(!1)&&!(0,m.F)(a,"voted")){var c=(0,m.F)(a,"id"),d=(0,m.w)("VIDEO_ID"),e=(0,m.F)(a,"score")||"0",g=b?1:-1;(0,m.qb)(a,"voted",g+"");b?(0,m.Ln)(a,"voted-down","voted-up"):(0,m.Ln)(a,"voted-up","voted-down");c={a:g,id:c,video_id:d,old_vote:e};(d=(0,m.F)(a,"tag"))&&(c.tag=d);(0,m.W)("/comment_voting",{format:"XML",method:"POST",da:c,ba:{session_token:(0,m.Vl)("comment_voting")}})}};
var FE=function(a){var b=(0,m.F)(a,"id"),c=(0,m.w)("VIDEO_ID");(0,m.V)(a,"has-child");(0,m.R)(a,"child");var d=(0,m.I)("parent-comment-loading");if(d){var e=(0,m.sn)(d);(0,m.ok)(e,a);m.P.show(e)}(0,m.W)("/comment_servlet?get_comment_parent=1",{format:"XML",method:"POST",ba:{comment_id:b,entity_id:c,session_token:(0,m.Vl)("comment_servlet")},onSuccess:function(b,c){var d=window.document.createElement("ul");d.innerHTML=c.html_content;d=(0,m.Hj)(d);(0,m.ok)(d,a);(0,m.Cc)(e);(0,m.Gl)(d)},onError:function(b,
c){(0,m.R)(a,"has-child");(0,m.V)(a,"child");(0,m.Cc)(e);c&&c.error_message?window.alert(c.error_message):window.alert("Request failed, please try later.")}})};var GE=function(){(0,m.go)((0,m.uw)())&&(0,m.go)((0,m.ww)())||HE();if((0,m.xw)()){var a=IE;"html5"!=a.getPlayerType()&&a.loadNewVideoConfig(a.getCurrentVideoConfig(),"html5")}};
var JE=function(a){var b=(0,m.yw)();if((0,m.fw)(b,a)&&(b=IE,"html5"!=b.getPlayerType())){var c=b.getVideoData().video_id,d=b.getCurrentTime(),d=(0,m.Yy)(d),e={key:a,videoId:c,currentTime:d},g="Setting the delayed connect data: "+(0,m.yn)(e);(0,m.py)(m.sy,"RC",g);!(0,m.Sy)(m.Hy.getInstance(),a)&&(a=(0,m.Ty)(m.Hy.getInstance(),a))&&(g=(0,m.ew)(),e.pairingCode=g,(0,m.Gy)(a.id,g,c,d));(0,m.Gf)("yt-remote-delayed-connect-key",e);b.loadNewVideoConfig(b.getCurrentVideoConfig(),"html5")}};
var HE=function(){var a=IE;a.updateRemoteReceivers&&a.updateRemoteReceivers((0,m.yw)())};
var KE=function(){if(!LE){var a=(0,m.n)("ytplayer.config");if(a&&(a=(0,m.ef)(a),LE=(0,m.Yf)("player-api",a),(0,m.Ma)("PLAYER_REFERENCE",LE),LE)){var b=LE;b.addEventListener("onReady",ME);b.addEventListener("onStateChange",NE);b.addEventListener("RATE_SENTIMENT",OE);b.addEventListener("SHARE_CLICKED",PE);b.addEventListener("SIZE_CLICKED",QE);b.addEventListener("onError",RE);b.addEventListener("WATCH_LATER_VIDEO_ADDED",SE);b.addEventListener("WATCH_LATER_VIDEO_REMOVED",TE);b.addEventListener("onAdStart",
UE);b=LE;(0,m.vy)();IE=b;IE.addEventListener("onReady",GE);IE.addEventListener("onRemoteReceiverSelected",JE);b=m.Hy.getInstance();b.N("onlineReceiverChange",HE);VE=(0,m.B)("yt-remote-cast-device-tab-projected",JE);a.args.has_mdx_screens?rC(b):(0,m.go)(b.vf)&&(0,m.go)((0,m.Iy)())||(b.log_("Clear cached account screens."),b.vf=[],b.zl(),b.Yi());WE();XE=(0,m.bo)(WE,1E3);YE.push((0,m.B)("player-shortcut-rewind",ZE));YE.push((0,m.B)("player-shortcut-fast-forward",$E));YE.push((0,m.B)("player-shortcut-play-pause",
aF));YE.push((0,m.B)("watch-list-change",bF));(0,m.FA)(LE);cF.push((0,m.B)("sentiment-like",(0,m.s)(m.jp,"like")),(0,m.B)("sentiment-dislike",(0,m.s)(m.jp,"dislike")),(0,m.B)("sentiment-indifferent",(0,m.s)(m.jp,"indifferent")));(0,m.w)("BG_P")&&((0,m.w)("BG_I")||(0,m.w)("BG_IU"))&&eE()}}};var bF=function(){var a=LE;a&&dF&&a.updatePlaylist()};
var eF=function(a,b){var c=fF();if(c){var d=(0,m.Vb)(c,"").split(","),d=(0,m.oc)(d,function(b){return 0!=b.indexOf(a)&&!!b.length});4<=d.length&&d.shift();d.push(a+":"+b);(0,m.Tb)(c,d.join(","),1814400)}};var gF=function(a){var b=fF();if(b){var c=(0,m.Vb)(b,"").split(","),c=(0,m.oc)(c,function(b){return 0!=b.indexOf(a)});0==c.length?(0,m.Sn)(b):(0,m.Tb)(b,c.join(","),1814400)}};
var hF=function(a){var b=(0,m.We)();if(b){a&&(0,m.Ma)("RESUME_COOKIE_NAME",a);a=(0,m.w)("VIDEO_ID");var c=b.getDuration(),b=Math.floor(b.getCurrentTime());0==c||120>=b||b+120>=c?gF(a):eF(a,Math.floor(b))}};var iF=function(){var a=LE;a&&a.sendAbandonmentPing&&a.sendAbandonmentPing();if(fF()&&(hF(),(0,m.w)("IS_RESUMABLE_PLAYBACK"))){var b=LE;if(b){var a=(0,m.w)("VIDEO_ID"),c=b.getDuration(),b=Math.floor(b.getCurrentTime());0==c||20>=b||(0,m.vd)("/save_resume_204?"+(0,m.Wb)({v:a,t:b.toString()}))}}};
var ME=function(){var a=(0,m.w)("PLAYER_REFERENCE");if(a){dF=!0;(0,m.M)(window,"beforeunload",iF);jF(a.getPlayerState());var b=(0,m.w)("RELATED_PLAYER_ARGS");b&&a&&a.updateVideoData&&a.updateVideoData(b)}};var NE=function(a){jF(a);(0,m.E)("player-state-change",a)};var RE=function(a){(0,m.E)("player-error",a)};var QE=function(a){(0,m.Tb)("wide",a?"1":"0");(0,m.E)("player-resize",a)};var OE=function(a){(0,m.ja)(a)&&(a={videoId:(0,m.w)("VIDEO_ID"),sentiment:a});(0,m.E)("player-sentiment",a.videoId,a.sentiment)};
var PE=function(){(0,m.E)("player-share")};var SE=function(a){(0,m.E)("WATCH_LATER_VIDEO_ADDED",a)};var TE=function(a){(0,m.E)("WATCH_LATER_VIDEO_REMOVED",a)};var UE=function(a){(0,m.E)("player-ad-start",a)};var aF=function(){var a=LE;a&&(2==a.getPlayerState()?a.playVideo():a.pauseVideo())};var $E=function(){var a=LE;if(a){var b=a.getCurrentTime();a.seekTo(b+10)}};var ZE=function(){var a=LE;if(a){var b=a.getCurrentTime();a.seekTo(b-10)}};
var kF=function(a,b){var c=LE;if(c){var d=null!=b?b:!0;c.seekTo(a,!0);d&&window.scroll(0,0);c.playVideo()}};var WE=function(){if(dF){var a=window.location.hash;a!=lF&&(lF=a,a=(0,m.Ul)(a),"t"in a&&a.t!=mF.t&&kF((0,m.ix)(a.t),!1),mF=a)}};var jF=function(a){nF||1!=a&&2!=a&&0!=a||(nF=!0,(0,m.E)("player-playback-start"))};var fF=function(){return(0,m.w)("RESUME_COOKIE_NAME")};
var oF=function(a,b){var c=3E3==b;if(a){var d=["guide"];c&&d.push("related");pF(d,function(){(0,m.y)(qF.guide)});qF.guide=(0,m.x)(function(){(0,m.T)(rF);sF(d,!1)},3E3)}!b||a&&c||(qF.related=(0,m.x)(function(){sF(["related"])},b));c=["comments"];(0,m.w)("DELAY_LOAD_FOOTER")&&c.push("footer");tF(c)};var pF=function(a,b){rF=(0,m.ln)((0,m.I)("guide-loading-toggle"),"click",function(c){b&&!1===b(c)||sF(a,!0)})};
var tF=function(a){var b=(0,m.I)((0,m.w)("IS_ACTIVE_LIVE_VIDEO")&&!(0,m.w)("IS_DISTILLER")?"watch7-sidebar-discussion":"watch-discussion");if((0,m.ii)(b)){(0,m.G)(b,"scrolldetect");(0,m.qb)(b,"scrolldetect-callback","comments-delay-load");var c=(0,m.w)("WATCH_COMMENTS_LOAD_DELAY_PLAYBACK")?(0,m.O)()+1E4:(0,m.O)()+1E3;(0,m.Hu)({"comments-delay-load":function(){if((0,m.w)("WATCH_COMMENTS_LOAD_DELAY_PLAYBACK")){var b=(0,m.s)(sF,a);nF?b():YE.push((0,m.B)("player-playback-start",b))}qF.comments=(0,m.x)((0,m.s)(sF,
a),c-(0,m.O)())}})}};var sF=function(a,b){var c=(0,m.w)("VIDEO_ID");c||(0,m.Da)(a,"comments");(0,m.Ba)(a,"comments")&&(0,m.xA)()&&(0,m.Da)(a,"comments");if(a&&a.length){var d={v:c};(0,m.Ba)(a,"comments")&&(0,m.w)("IS_DISTILLER")&&(d.distiller="1");var e=(0,m.Rn)(window.location.href);e&&(0,m.C)(uF,function(a){a in e&&(d[a]=e[a])});(0,m.nt)(a,b,d,(0,m.s)(vF,a))}};
var vF=function(a){if((0,m.Ba)(a,"comments")){if(!(0,m.xA)()){var b=(0,m.I)("comments-view");wF=new sE((0,m.I)("watch-discussion"));xF.push((0,m.X)(b,"click",xE,"comment-action"));if(b=(0,m.I)("comments-textarea"))b.disabled=!1,b.id="";(0,m.w)("COMMENT_OPEN_REPLY_BOX")&&(b=(0,m.J)("comment",(0,m.I)("linked-comments-header")),DE(b[b.length-1]));(0,m.Gl)((0,m.I)("comments-view"))}(b=(0,m.w)("JS_COMMENTS_MODULES"))&&(0,m.wb)(b)}(0,m.Ba)(a,"related")&&((0,m.Gl)((0,m.I)("watch-related")),a=(0,m.w)("RELATED_PLAYER_ARGS"),
b=(0,m.w)("PLAYER_REFERENCE"),a&&b&&b.updateVideoData&&b.updateVideoData(a),(0,m.w)("SKIP_RELATED_ADS")||DD())};var yF=function(a,b,c){this.b=a;this.i=b;this.A=this.L=this.S=this.P=this.R=this.M=this.Q=this.X=this.$=this.k=this.C=this.B=this.g=this.j=this.G=this.D=null;this.L=(0,m.W)("/playlist_ajax",{da:{action_get_addto_panel:1,video_id:this.i},onSuccess:function(a,b){zF(this,b.html);c()},O:this})};
var zF=function(a,b){a.b.innerHTML=b;a.G=(0,m.Q)("sort-playlists",a.b);a.j=(0,m.Q)("playlist-items",a.b);a.g=(0,m.Q)("added-to-message",a.b);a.B=(0,m.Q)("messages-area",a.b);a.C=(0,m.Q)("create-playlist",a.b);a.C&&(a.k=(0,m.Q)("new-playlist-title",a.b),a.$=(0,m.Q)("create-new-playlist",a.b));a.X=(0,m.M)(a.G,"change",(0,m.r)(a.PA,a));a.Q=(0,m.M)(a.C,"submit",(0,m.r)(a.TA,a));a.M=(0,m.X)(a.b,"click",(0,m.r)(a.RA,a),"playlist-item");a.R=(0,m.X)(a.b,"click",(0,m.r)(a.SA,a),"save-note");a.P=(0,m.X)(a.b,
"click",(0,m.r)(a.QA,a),"cancel-note");a.S=(0,m.M)(a.k,"keyup",(0,m.r)(a.UA,a));AF(a,a.G.value);(0,m.Dp)()};var BF=function(a){(0,m.T)(a.X);(0,m.T)(a.Q);(0,m.T)(a.M);(0,m.T)(a.R);(0,m.T)(a.P);(0,m.T)(a.S)};var AF=function(a,b){var c={updated:(0,m.s)(a.Lv,"time-updated"),created:(0,m.s)(a.Lv,"time-created"),privacy:a.FH,"a-z":a.Mv,"z-a":a.GH}[b];if(c){var d=(0,m.Ga)((0,m.J)("playlist-item",a.j));CF(a,d.sort((0,m.r)(c,a)))}};
var CF=function(a,b){var c=window.document.createDocumentFragment();(0,m.C)(b,function(a){c.appendChild(a)});(0,m.Bc)(a.j);(0,m.zc)(a.j,c)};var DF=function(a,b){(0,m.G)(b,"loading");m.P.hide(a.g);a.A=(0,m.xn)(b,{O:a,onSuccess:function(a,d){(0,m.H)(b,"loading");d.html?(BF(this),zF(this,d.html),d.show_feed_privacy_dialog&&(0,m.E)("SHOW-FEED-PRIVACY-ADD-TO-PLAYLIST-DIALOG",d.video_id,d.playlist_id)):d.errors&&EF(this,d.errors[0],!0)}})};
var FF=function(a,b){var c=(0,m.Q)("playlist-video-count",a);c.innerHTML=(0,window.parseInt)(c.innerHTML,10)+b};var GF=function(a,b){(0,m.G)(b,"loading");(0,m.xn)(b,{format:"XML",ba:{session_token:(0,m.Vl)("addto_ajax"),setvideo_id:a.D},O:a,onSuccess:function(a,d){HF(this);(0,m.H)(b,"loading");d.html_content&&EF(this,d.html_content,!1)},onError:function(a,d){(0,m.H)(b,"loading");EF(this,d.errors[0],!0)}})};var HF=function(a){var b=(0,m.Q)("selected",a.b);b&&((0,m.H)(b,"selected"),a.D=null)};
var EF=function(a,b,c){c?(0,m.ys)("yt-alert-error",b,a.g,a.B):(0,m.ys)("yt-alert-success",b,a.g,a.B)};var IF=function(){(0,m.rk)("yt.net.apiloader.onApiLoaded_GOOGLE_JSAPI",function(){JF()})};var JF=function(){KF.GOOGLE_JSAPI=!0;(0,m.C)(LF.GOOGLE_JSAPI,function(a){a.call()});delete LF.GOOGLE_JSAPI};
var MF=function(a){this.j=a;this.i=[];this.B=this.Cn=!1;this.A=this.b=this.k=this.g=null;var b=(0,m.r)(this.C,this),c=(0,m.w)("HL_LOCALE")||"en";if(a=NF.GOOGLE_JSAPI)KF.GOOGLE_JSAPI?b.call():(LF.GOOGLE_JSAPI||(LF.GOOGLE_JSAPI=[]),LF.GOOGLE_JSAPI.push(b),OF.GOOGLE_JSAPI||(IF(),b={callback:"yt.net.apiloader.onApiLoaded_GOOGLE_JSAPI"},c&&(b.language=c),a=(0,m.Pb)(a,b),c=window.document.createElement("script"),c.src=a,window.document.body.appendChild(c),OF.GOOGLE_JSAPI=!0))};
var PF=function(a,b){var c=(0,m.I)("stats-optout-form");c&&(m.P.hide("stats-optout-success"),m.P.hide("stats-optout-error"),a.A=(0,m.xn)(c,{format:"XML",da:{opt_out:b},onSuccess:function(){this.Cn=b;m.P.show("stats-optout-success")},onError:function(){(0,m.I)("stats-opt-out-chbox").checked=!this.Cn;m.P.show("stats-optout-error")}}))};var QF=function(a,b){var c=(0,m.F)(a,b);if(c){var d=(0,m.L)(a,"watch-actions-stats-rats"),e=(0,m.F)(d,"current-"+b);e!=c&&((0,m.Ln)(d,e,c),(0,m.qb)(d,"current-"+b,c))}};
var RF=function(a,b,c){a=(0,m.Q)("watch-actions-stats-rats",a.j);if(!a)return null;b=(0,m.F)(a,"current-"+b);return c&&b&&0==b.lastIndexOf(c,0)?b.substr(c.length):b};var SF=function(a){if(a.g&&a.B&&a.k){var b=RF(a,"metric-css","stats-metric-"),c=RF(a,"mode-css","stats-mode-");b&&c&&(a.b||(a.b=new window.google.visualization.LineChart(a.k)),TF(a,a.b,a.k,a.g.day||{},b in a.g?a.g[b][c]||{}:{}))}};
var TF=function(a,b,c,d,e){var g=new window.google.visualization.DataTable;g.addColumn("date","Date");g.addColumn("number","value");"cmp_data"in e?(g.addColumn("number","cmp_data"),d=uD(d.data||[],e.data||[],e.cmp_data||[])):d=uD(d.data||[],e.data||[]);(0,m.C)(d,function(a){a[0]=UF(a[0]);g.addRow(a)});e=e.opt||{};"hAxis"in e&&"viewWindow"in e.hAxis&&(d=e.hAxis.viewWindow,"min"in d&&!(d.min instanceof Date)&&(d.min=UF(d.min)),"max"in d&&!(d.max instanceof Date)&&(d.max=UF(d.max)));d=(0,m.xi)(c);(0,m.Cc)(c);
c.style.left="-5000px";(0,m.zc)(a.j,c);try{b.draw(g,e)}catch(h){throw h;}finally{c.style.left="",(0,m.Cc)(c),d&&(0,m.zc)(d,c)}};var UF=function(a){return new Date(a+6E4*(new Date(a)).getTimezoneOffset())};
var VF=function(a,b){this.B=a;this.C=b;this.g=(0,m.I)("watch-like-dislike-buttons");this.i="action-panel-details";var c=(0,m.F)(this.g,"vote-state"),c=(0,window.parseInt)(c,10);(0,window.isNaN)(c)&&(c=2);(0,m.qj)(this.g,"vote-state");this.j=c;this.b=[];this.be=[];this.gn=this.ln=this.A=this.k=null;this.D=this.Zq=0;WF(this);XF(this,this.i);c=(0,m.Ul)(window.location.hash).action;"share"==c?this.wr():"flag"==c?YF(this,"action-panel-report"):"stats"==c&&YF(this,"action-panel-stats");(0,m.w)("RECIPROCAL_CIRCLE_ADD_PROMO")&&
ZF(this)};var $F=function(a){switch(a){case "action-panel-share":(0,m.qo)("share");(0,m.w)("CONVERSION_CONFIG_DICT")&&(0,m.gp)("share",(0,m.w)("CONVERSION_CONFIG_DICT").uid||"");break;case "action-panel-addto":(0,m.qo)("add_to_playlist")}};
var WF=function(a){a.be.push((0,m.B)("player-share",a.wr,a));a.be.push((0,m.B)("player-state-change",a.BF,a));a.be.push((0,m.B)("player-sentiment",a.vF,a));a.be.push((0,m.B)("livestreaming-likes-updated",a.AF,a));a.b.push((0,m.X)(a.B,"click",(0,m.r)(a.uF,a),"action-panel-trigger"));if((0,m.w)("LOGGED_IN")){var b=(0,m.I)("watch-dislike");a.b.push((0,m.M)((0,m.I)("watch-like"),"click",(0,m.r)(a.tF,a)));a.b.push((0,m.M)(b,"click",(0,m.r)(a.sF,a)));(0,m.w)("WATCH_STATS_RATING_BUTTONS")&&(b=(0,m.I)("watch-stats-dislike"),
a.b.push((0,m.M)((0,m.I)("watch-stats-like"),"click",(0,m.r)(a.yF,a))),a.b.push((0,m.M)(b,"click",(0,m.r)(a.xF,a))))}(b=(0,m.I)("watch-share-button"))&&a.b.push((0,m.M)(b,"click",(0,m.r)(a.wF,a)));var c=(0,m.I)("donation-box");if(c){var d=(0,m.Q)("google-checkout-price",c);a.b.push((0,m.M)(d,"change",function(){(0,m.Q)("google-checkout-donate",c).disabled=1>d.selectedIndex}));if(b=(0,m.I)("watch-donation-button")){var e=new m.Wz;(0,m.nx)(e,b);(0,m.v)(a,e)}}a.be.push((0,m.B)("watch-video-liked",(0,m.r)(a.zF,
a)))};
var aG=function(a,b,c){bG(!1);(0,m.ro)(b,c,{yb:(0,m.w)("PLAYBACK_ID"),cv:(0,m.w)("STATION_ID"),onSuccess:(0,m.r)(function(a,e){var g;t:switch(c){case 1:g="sentiment-dislike";break t;case 0:g="sentiment-like";break t;default:g="sentiment-indifferent"}(0,m.E)(g,b);0==c?((0,m.E)("watch-video-liked"),(0,m.Ln)(this.g,"disliked","liked")):1==c?((0,m.E)("watch-video-disliked"),(0,m.Ln)(this.g,"liked","disliked")):(0,m.V)(this.g,"liked","disliked");g=(0,m.I)("watch-like");var h;if(h=0==c?(0,m.F)(g,"unlike-tooltip"):
(0,m.F)(g,"like-tooltip"))(0,m.qj)(g,"tooltip-text"),g.title=h;this.j=c;0==c&&"True"==e.show_feed_privacy_dialog&&(0,m.E)("SHOW-FEED-PRIVACY-LIKE-DIALOG",b)},a),onError:(0,m.r)(function(){cG(this,"action-panel-error")},a),Ca:(0,m.r)(function(){bG(!0)},a)})};var bG=function(a){var b=(0,m.I)("watch-like-dislike-buttons");(0,m.x)(function(){(0,m.rn)(b,a)},0)};var dG=function(a,b){YF(a,"action-panel-share",b)};
var YF=function(a,b,c){var d=(0,m.I)("watch7-secondary-actions");uC(m.Cd.getInstance(),d);d=eG(a,(0,m.I)(b));(0,m.R)(d,"yt-uix-button-toggled");XF(a,b,c)};var fG=function(a){return(0,m.w)("ALLOW_RATINGS")?(0,m.w)("LOGGED_IN")?(0,m.w)("YPC_CAN_RATE_VIDEO")?!0:(cG(a,"action-panel-rental-required"),!1):(cG(a,"action-panel-login"),!1):(cG(a,"action-panel-ratings-disabled"),!1)};
var XF=function(a,b,c){if("action-panel-none"!=b){var d=(0,m.I)(b),e=!!(0,m.F)(d,"auth-required"),d=!!(0,m.F)(d,"panel-loaded");if(e&&!(0,m.w)("LOGGED_IN"))cG(a,"action-panel-login");else if(d)cG(a,b);else switch(b){case "action-panel-details":b=(0,m.I)("action-panel-details");gG(a);(0,m.qb)(b,"panel-loaded","true");cG(a,"action-panel-details");break;case "action-panel-share":hG(a,c);break;case "action-panel-addto":b=(0,m.I)("action-panel-addto");c=new yF(b,(0,m.w)("VIDEO_ID"),m.da);(0,m.v)(a,c);
(0,m.qb)(b,"panel-loaded","true");cG(a,"action-panel-addto");break;case "action-panel-transcript":iG(a);break;case "action-panel-stats":jG(a);break;case "action-panel-report":kG(a)}}};
var gG=function(a){var b=(0,m.Q)("yt-uix-expander",(0,m.I)("action-panel-details"));b&&(a.b.push((0,m.M)((0,m.I)("watch-description-content"),"click",function(){if((0,m.uc)(b,"yt-uix-expander-collapsed")){var a=m.xp.getInstance(),d=a.ya(b);d&&((0,m.V)(d,(0,m.N)(a,"collapsed")),a.i(d,"expander-action"))}})),(0,m.uc)(b,"yt-uix-expander-collapsed")&&a.b.push((0,m.ln)(b,"click",function(){var a=(0,m.I)("watch-source-videos-list");a&&(this.ln=lD(a))})))};
var hG=function(a,b){var c=pD(),d=oD(),e=(0,m.I)("action-panel-share"),g=new m.zB((0,m.I)("watch-actions-share-panel"),c,d,function(){m.P.hide("watch-actions-share-loading")},!0,null,b,!1,(0,m.w)("SHARE_CAPTION"));(0,m.v)(a,g);var h=(0,m.bo)(function(){var a=(0,m.We)(),b=m.P.fb(e);if(a&&b){var a=a.getCurrentTime(),b=Math.floor(a/3600),c=Math.floor(a%3600%60),a=(0<b?b+":":"")+(0,m.jo)(Math.floor(a%3600/60),0<b?2:1)+":"+(0,m.jo)(c,2);g.nj(a)}else(0,m.ao)(h)},1E3);a.D=h;(0,m.qb)(e,"panel-loaded","true");
cG(a,"action-panel-share")};var jG=function(a){var b=(0,m.I)("action-panel-stats");if(b){var c=new MF(b);(0,m.v)(a,c);a.A=mD((0,m.r)(function(a,e,g){g?(b.innerHTML=a,c.load(e)):cG(this,"action-panel-error")},a));(0,m.qb)(b,"panel-loaded","true");cG(a,"action-panel-stats")}};
var kG=function(a){var b,c=!1,d=!1,e=(0,m.I)("action-panel-report"),g=(0,m.r)(function(){cG(this,"action-panel-error")},a);(0,m.nf)((0,m.w)("REPORTVIDEO_CSS"));(0,m.tb)((0,m.w)("REPORTVIDEO_JS"),(0,m.r)(function(){this.oa()||(c=!0,d&&c&&lG(e,b))},a));a.k=nD((0,m.r)(function(a,k){k?(d=!0,b=a,d&&c&&lG(e,b)):g()},a));(0,m.qb)(e,"panel-loaded","true");cG(a,"action-panel-report")};var lG=function(a,b){a.innerHTML=b;(0,m.n)("yt.www.report.reportvideo.init")(!0)};
var iG=function(a){var b=(0,m.I)("action-panel-transcript");(0,m.n)("yt.www.watch.transcript.open")(function(){m.P.hide("watch-actions-transcript-loading");m.P.show((0,m.I)("watch-actions-transcript"))});(0,m.qb)(b,"panel-loaded","true");cG(a,"action-panel-transcript")};
var cG=function(a,b){var c=mG[a.i],d=mG[b],e=(0,m.I)(a.i),g=(0,m.I)(b),h=a.C;if(d==c)(0,m.V)(h,"action-panel-transition"),(0,m.V)(e,"action-panel-center","action-panel-left","action-panel-right"),m.P.show(e);else{a.i=b;m.P.show(e);h.style.height=h.clientHeight+"px";(0,m.R)(h,"action-panel-transition");if(d>c)var k="action-panel-right",p="action-panel-left";else k="action-panel-left",p="action-panel-right";(0,m.R)(e,"action-panel-center");(0,m.R)(g,k);m.P.show(g);(0,m.x)(function(){(0,m.V)(e,"action-panel-center");
(0,m.R)(e,p);(0,m.V)(g,k);(0,m.R)(g,"action-panel-center");this.Zq=(0,m.x)(function(){m.P.hide(e);(0,m.V)(e,p);(0,m.V)(g,"action-panel-center");(0,m.V)(h,"action-panel-transition");h.style.height=""},(0,m.Nl)(g))},0)}};var eG=function(a,b){var c=(0,m.J)("action-panel-trigger",a.B);return(0,m.za)(c,function(a){a=(0,m.F)(a,"trigger-for");return b.id==a})};
var ZF=function(a){var b=(0,m.Q)("yt-uix-clickcard-target",(0,m.I)("watch7-user-header")),c=(0,m.Q)("rcap-dismiss-button",window.document);(0,m.es)("plus:follow",(0,m.fs)(function(){var a=(0,m.Q)("add-to-circle"),b=(0,m.n)("gapi.follow.render");b&&a&&(b(a,{href:(0,m.F)(a,"gplus-profile-url"),height:24,source:"youtube:topfans-follow-back"}),a.style.zIndex=2147483647)}));a.b.push((0,m.M)(c,"click",function(){this.gn=(0,m.W)("/engagement_wizard_ajax",{method:"POST",da:{action_dismiss_reciprocal_circle_add_promo:"1"},
ba:{session_token:(0,m.Vl)("engagement_wizard_ajax"),video_id:(0,m.w)("VIDEO_ID")}})}));m.vp.getInstance().show(b)};var nG=function(){this.b=[];this.g=0;this.i=window.document.title;(0,m.We)()&&this.Ut(1);this.b.push((0,m.B)("page-resize",this.iD,this));this.b.push((0,m.B)("player-state-change",this.Ut,this));this.b.push((0,m.B)("player-resize",this.jD,this));this.fl()};var oG=function(a){1==a&&(0,m.tm)()};
var pG=function(a,b){if(!qG&&b.swfcfg){var c=b.swfcfg.args,d=LE;d&&d.preloadVideoByPlayerVars&&c&&d.preloadVideoByPlayerVars(c);qG=!0}};var rG=function(a){(0,m.Ic)(a.target,"BUTTON")||a.currentTarget.click()};var sG=function(a,b){b.subscriptionId&&window.location.reload(!0)};m.tB.prototype.nj=(0,m.ck)(31,function(){if(this.kx){var a=(0,m.We)(),b=Math.round(1E3*a.getCurrentTime()),b=[b,b+1E3],b=(0,m.uB)(this,b,!0);(0,m.xB)(this,b,1!=a.getPlayerState())}});
m.zB.prototype.nj=(0,m.ck)(30,function(a){!this.g||(0,m.uc)(this.g,"focused")||this.ia||(this.g.value=a,this.gi(),m.P.fb(this.k)&&this.M&&this.M.nj())});var zC="",IC=null,HC=null,BC=null,tC=null,PC=null,tG=[],VC=null,$C=null,bD=null,cF=[],sD=[],rD=[],wF,wE,uG,vG;m.f=vD.prototype;m.f.sg=!1;m.f.Xi=!1;
m.f.start=function(a){var b={start:0};b.end=a.scrollHeight-a.clientHeight;b.duration=b.end/3;b.Ni="linear";this.b=new m.zv(a,b);this.sg=!0;this.g.listen(a,"click",this.BE);this.g.listen(a,"mouseover",this.DE);this.g.listen(a,"mouseout",this.AE);this.g.listen(a,"scroll",this.CE)};m.f.CE=function(){this.Xi||this.sg||(this.b.pause(),this.Xi=!0)};m.f.BE=function(){this.b.pause();this.sg=!1;this.Xi=!0};m.f.DE=function(){this.b.pause();this.sg=!1};
m.f.AE=function(){this.sg||this.Xi||(this.b.play(),this.sg=!0)};m.f.dispose=function(){this.g.removeAll();this.Xi=this.sg=!1;this.b=null;this.i=!0};m.f.oa=function(){return this.i};var xD,zD,YD="",ZD="",cE=!1,JD=!1,LD=null,AD=null,dE=0,MD=null,ND=null,OD=null,KD=!1;(0,m.l)("yt.www.watch.ads.setAdId",function(a){window.ad_debug=a},void 0);(0,m.l)("yt.www.watch.ads.setCompanion",PD,void 0);(0,m.l)("yt.www.watch.ads.showForcedMpu",function(a){var b=RD(a,250);a=SD(a);PD(b,a)},void 0);(0,m.l)("yt.www.watch.ads.createGutSlot",ED,void 0);
(0,m.l)("yt.www.watch.ads.handleMoveGutCompanion",function(){var a=(0,m.I)("google_companion_ad_div"),b=(0,m.I)("yt-gut-content");b?b.innerHTML="":(b=window.document.createElement("div"),b.id="yt-gut-content");a&&(a.innerHTML="",a.appendChild(b));QD()},void 0);(0,m.l)("yt.www.watch.ads.setGutSlotSizes",function(a,b){if(MD){var c=MD.getSizes();(0,m.fo)(c);b&&c.push(ND);a&&c.push(OD)}},void 0);(0,m.l)("yt.www.watch.ads.handleSetCompanion",TD,void 0);
(0,m.l)("yt.www.watch.ads.handleSetCompanionForInstream",UD,void 0);(0,m.l)("yt.www.watch.ads.handleSetCompanionForFreewheel",VD,void 0);(0,m.l)("yt.www.watch.ads.handleHideCompanion",PD,void 0);(0,m.l)("yt.www.watch.ads.handleHideCompanionForInstream",PD,void 0);(0,m.l)("yt.www.watch.ads.handleCloseMpuCompanion",PD,void 0);(0,m.l)("yt.www.watch.ads.handleSetAfvCompanionVars",WD,void 0);(0,m.l)("yt.www.watch.ads.handleShowAfvCompanionAdDiv",aE,void 0);
(0,m.l)("yt.www.watch.ads.handleHideAfvInstreamCompanionAdDiv",bE,void 0);(0,m.l)("yt.www.watch.ads.AD_LOAD_TOPIC","watchads-adLoad",void 0);(0,m.l)("yt.www.watch.ads.companionSetupComplete",XD,void 0);(0,m.l)("yt.www.watch.ads.pauseVideo",$D,void 0);(0,m.l)("yt.www.watch.ads.loadAfc",FD,void 0);(0,m.l)("yt.www.watch.ads.isAfcAdVisible",function(){var a=(0,m.I)("google_companion_ad_div");return a?(a=(0,m.Hj)(a))&&"IFRAME"==a.tagName?-1!=a.src.indexOf("youtube.com/ad_frame"):!1:!1},void 0);
(0,m.l)("yt.www.watch.ads.checkInit",GD,void 0);(0,m.l)("yt.www.ads.pyv.pyvWatchAfcWithPpvCallback",function(a){jD(a);0<a.length&&iD()},void 0);(0,m.l)("yt.www.ads.pyv.pyvWatchAfcCallback",jD,void 0);(0,m.l)("yt.www.ads.pyv.pyvHomeAfcCallback",m.ez,void 0);(0,m.l)("yt.www.ads.pyv.showPpvOnWatch",NC,void 0);(0,m.l)("yt.www.ads.pyv.loadPyvIframe",hD,void 0);(0,m.l)("setCompanion",TD,void 0);(0,m.l)("setInstreamCompanion",UD,void 0);(0,m.l)("setFreewheelCompanion",VD,void 0);
(0,m.l)("closeInPageAdIframe",PD,void 0);(0,m.l)("hideInstreamCompanion",PD,void 0);(0,m.l)("closeMpuCompanion",PD,void 0);(0,m.l)("setAfvCompanionVars",WD,void 0);(0,m.l)("showAfvCompanionAdDiv",aE,void 0);(0,m.l)("hideAfvInstreamCompanionAdDiv",bE,void 0);(0,m.l)("setVideoWallCompanionTrackingUrl",function(a,b){YD=a;ZD=b;window.addEventListener("message",function(a){"companion-setup-complete"==a.data?XD():"pause-video"==a.data&&$D()},!1)},void 0);var fE=null;m.f=kE.prototype;m.f.destroy=function(){(0,m.T)(this.k);this.k=[];(0,m.C)(this.j,function(a){(0,m.ao)(a)});this.j=[];(0,m.qj)(this.Za,"initialized")};m.f.reset=function(){nE(this);pE(this);(0,m.V)(this.Za,"has-focus");this.jf.disabled=!1;this.Ic.value="";lE(this);this.Ic.blur();this.i=null;this.destroy();(0,m.E)("comment-form-reset")};m.f.focus=function(){this.Ic.focus()};m.f.Tr=function(){this.Ic.readOnly||lE(this)};m.f.Tz=function(a){if(this.B)switch(a.keyCode){case 13:this.Sr(a);break;case 27:this.reset()}};
m.f.Ur=function(){(0,m.uc)(this.Za,"has-focus")||m.P.hide(this.Yf);(0,m.R)(this.Za,"has-focus");(0,m.E)("comments-focus",this.Za)};m.f.Sz=function(){(0,m.E)("comments-blur",this.Za)};
m.f.Sr=function(a){a.preventDefault();if(!this.jf.disabled){this.jf.disabled=!0;this.Ic.readOnly=!0;a=(0,m.cl)((0,m.Dm)(this.Za));a.screen=(0,m.Wb)({h:window.screen.height,w:window.screen.width,d:window.screen.colorDepth});var b=a.comment,b={return_ajax:"true",len:b.length,wc:b.split(/\s+/).length};this.Za.reply_parent_id.value&&(b.reply=1);this.i&&(b.tag=this.i);var c=(0,m.w)("PLAYBACK_ID");c&&(a.plid=c);(0,m.W)(this.Za.action,{format:"XML",method:"POST",da:b,ba:a,Ca:function(a,b){var c=b.str_code;
switch(c){case "OK":c=window.document.createElement("ul");c.innerHTML=b.html_content;c=(0,m.Hj)(c);if(this.Za.reply_parent_id.value){var h=(0,m.Ic)(this.Za,null,"comments-post-container"),k=(0,m.Ic)(h,null,"comment");(0,m.Cc)(h);(0,m.Ln)(k,"replying","has-child");(0,m.R)(c,"child");(0,m.Gm)(c,"last",!(0,m.tl)(k));(0,m.Hn)(c,k)}else this.Vy?this.Dr.appendChild(c):(0,m.Ij)(this.Dr,c,0),this.reset();(0,m.gl)(c);(0,m.E)("comment-submit-success");"True"==b.show_feed_privacy_dialog&&(0,m.E)("SHOW-FEED-PRIVACY-COMMENT-DIALOG",
(0,m.w)("VIDEO_ID"),b.time_created);break;case "PENDING":nE(this);this.Cr.innerHTML=(0,m.A)("COMMENT_PENDING");(0,m.Ln)(this.Yf,"yt-alert-error","yt-alert-info");m.P.show(this.Yf);break;default:rE(this,c,b)}this.Ic.readOnly=!1},O:this});(0,m.w)("CONVERSION_CONFIG_DICT")&&(0,m.gp)("comment",(0,m.w)("CONVERSION_CONFIG_DICT").uid||"");(0,m.qo)("comment")}};sE.prototype.destroy=function(){(0,m.T)(this.b);this.b=[]};sE.prototype.j=function(a){a.preventDefault();(0,m.uc)(a.currentTarget,"yt-uix-button-toggled")||(m.P.hide(this.Ss),(0,m.E)("comments-page-changing"),this.pj?this.g(2):tE(this,(0,m.r)(this.g,this,2)))};
sE.prototype.g=function(a){var b=(0,m.I)("comments-view");b.appendChild(this.pj);(0,m.gl)(b);if(b=(0,m.I)("comments-textarea"))b.disabled=!1,b.id="";if(b=(0,m.Q)("comment-list",this.aa)){var c=(0,m.Q)("live-comments-setting",this.aa);(0,m.E)("comments-page-changed",b,c,a)}else(0,m.E)("comments-page-changed");tE(this)};var xF=[];var IE=null,VE=window.NaN;var LE,YE=[],dF=!1,nF=!1,lF="",mF={},XE=0;var rF,qF={},uF="lc lch lcor lcai generate_fake_live_comments debugjs".split(" ");(0,m.t)(yF,m.Ia);m.f=yF.prototype;m.f.J=function(){this.L&&this.L.abort();this.A&&this.A.abort();BF(this);yF.F.J.call(this)};m.f.PA=function(a){a=a.currentTarget.value;AF(this,a);(0,m.W)("/playlist_ajax?action_update_addto_sort_criteria=1",{da:{criteria:a}})};m.f.FH=function(a,b){var c=(0,m.F)(a,"is-private")||"",d=(0,m.F)(b,"is-private")||"";return(0,m.$l)(c,d)};
m.f.Lv=function(a,b,c){b=(0,window.parseInt)((0,m.F)(b,a),10)||window.Infinity;return((0,window.parseInt)((0,m.F)(c,a),10)||window.Infinity)-b};m.f.Mv=function(a,b){var c=(0,m.F)(a,"title")||"",d=(0,m.F)(b,"title")||"";return(0,m.$l)(c,d)};m.f.GH=function(a,b){return this.Mv(b,a)};m.f.TA=function(a){a.preventDefault();a=(0,m.Q)("create-playlist",this.b);(0,m.Wm)(this.k.value)||DF(this,a)};
m.f.RA=function(a){if(!(0,m.L)(a.target,"playlist-note-form"))if(a.stopPropagation(),HF(this),m.P.hide(this.g),a=a.currentTarget,(0,m.nc)(a,"contains-selected-videos")){var b=(0,m.F)(a,"full-list-id");(0,m.G)(a,"loading");(0,m.Jt)({hb:this.i,$i:b,onSuccess:(0,m.s)(this.KF,a),onError:(0,m.s)(this.Ou,a),O:this})}else{var b=(0,m.F)(a,"full-list-id"),c=(0,m.I)("playlist-addto-top-checkbox").checked?"True":"False";(0,m.G)(a,"loading");(0,m.It)({hb:this.i,$i:b,CF:c,onSuccess:(0,m.s)(this.JF,a),onError:(0,m.s)(this.Ou,
a),O:this})}};m.f.KF=function(a,b,c){(0,m.pj)(a,["loading","contains-selected-videos"]);FF(a,-1);c.html_content&&EF(this,c.html_content,!1);(0,m.E)("PLAYLIST_UPDATED")};
m.f.JF=function(a,b,c){this.D=c.setvideo_id;(0,m.qk)(a,"loading","contains-selected-videos");FF(a,1);c.html_content&&EF(this,c.html_content,!1);"True"==c.show_private_video_warning&&(b=(0,m.Q)("private-video-warning",(0,m.Q)("watch-playlist-drawer")))&&m.P.show(b);b=(0,m.F)(a,"list-type");var d="favorites"==b;d||"watch-later"==b||(0,m.G)(a,"selected");d?(a="playlist-favorite",b="SHOW-FEED-PRIVACY-FAVORITE-DIALOG"):(a="playlist-addto",b="SHOW-FEED-PRIVACY-ADD-TO-PLAYLIST-DIALOG");(0,m.E)(a,this.i,
c.full_list_id);"True"==c.show_feed_privacy_dialog&&(0,m.E)(b,this.i,c.full_list_id);(0,m.E)("PLAYLIST_UPDATED")};m.f.Ou=function(a,b,c){(0,m.H)(a,"loading");EF(this,c.error_message,!0)};m.f.SA=function(a){a.preventDefault();m.P.hide(this.g);a=(0,m.L)(a.currentTarget,"playlist-note-form");GF(this,a)};m.f.QA=function(){HF(this)};m.f.UA=function(){this.$.disabled=(0,m.Wm)(this.k.value)};var NF={GOOGLE_MAPS_API:"//maps.google.com/maps/api/js?sensor=false",GOOGLE_LANGUAGE_API_VIRTUAL_KEYBOARD:"//www.google.com/jsapi?key=youtube-internal-vk",GOOGLE_LANGUAGE_API_INPUT_TOOLS:"//www.google.com/jsapi?key=youtube-internal-it",GOOGLE_PLUS_ONE:"//apis.google.com/js/platform.js",GOOGLE_JSAPI:"//www.google.com/jsapi"},OF={},KF={},LF={};(0,m.t)(MF,m.Ia);MF.prototype.J=function(){(0,m.T)(this.i);this.i.length=0;this.A&&this.A.abort();this.b&&(this.b.clearChart(),this.b=null);MF.F.J.call(this)};
MF.prototype.load=function(a){var b=(0,m.I)("stats-opt-out-chbox");b&&(this.Cn=!b.checked,this.i.push((0,m.M)(b,"change",(0,m.r)(function(){PF(this,!b.checked)},this))));this.i.push((0,m.X)(this.j,"click",(0,m.r)(function(a){QF(a.currentTarget,"mode-css");SF(this)},this),"stats-mode-button"));this.i.push((0,m.X)(this.j,"click",(0,m.r)(function(a){QF(a.currentTarget,"top-site-css");QF(a.currentTarget,"metric-css");SF(this)},this),"stats-bragbar"));(0,m.gn)(m.Nq);a&&(this.g=(0,m.Yk)(a));this.k=(0,m.Q)("stats-chart-gviz",
this.j);SF(this)};MF.prototype.C=function(){window.google.load("visualization","1.0",{packages:["corechart"],callback:(0,m.r)(this.D,this),language:(0,m.w)("HL_LOCALE")||"en"})};MF.prototype.D=function(){this.B=!0;SF(this)};(0,m.t)(VF,m.Ia);var mG={"action-panel-details":1,"action-panel-share":2,"action-panel-addto":3,"action-panel-transcript":4,"action-panel-stats":5,"action-panel-report":6,"action-panel-login":7,"action-panel-ratings-disabled":8,"action-panel-rental-required":9,"action-panel-error":10};m.f=VF.prototype;
m.f.J=function(){(0,m.T)(this.b);this.b.length=0;(0,m.eb)(this.be);this.be.length=0;(0,m.y)(this.Zq);(0,m.ao)(this.D);this.k&&this.k.abort();this.A&&this.A.abort();this.ln&&this.ln.abort();this.gn&&this.gn.abort();VF.F.J.call(this)};m.f.tF=function(){var a=0==this.j?2:0;fG(this)&&aG(this,(0,m.w)("VIDEO_ID"),a)};m.f.sF=function(){var a=1==this.j?2:1;fG(this)&&aG(this,(0,m.w)("VIDEO_ID"),a)};m.f.yF=function(){(0,m.vk)("action=statsclick&sentiment=like")};m.f.xF=function(){(0,m.vk)("action=statsclick&sentiment=dislike")};
m.f.zF=function(){YF(this,"action-panel-share")};m.f.wr=function(){dG(this);$F("action-panel-share")};m.f.BF=function(a){0==a?(0,m.w)("SHARE_ON_VIDEO_END")&&dG(this,!0):((0,m.w)("SHARE_ON_VIDEO_PAUSE")&&2==a&&20<(0,m.We)().getCurrentTime()&&dG(this,!0),1==a&&(0,m.w)("SHARE_ON_VIDEO_START")&&dG(this,!0))};m.f.wF=function(){var a=(0,m.I)("watch7-secondary-actions");uC(m.Cd.getInstance(),a)};m.f.vF=function(a,b){fG(this)&&aG(this,a,b)};
m.f.uF=function(a){a=(0,m.F)(a.currentTarget,"trigger-for");var b=(0,m.I)("watch-share-button");b&&(0,m.uc)(b,"yt-uix-button-toggled")&&(0,m.V)(b,"yt-uix-button-toggled");XF(this,a);$F(a)};m.f.AF=function(a,b,c,d){var e=(0,m.I)("watch7-views-info"),g=(0,m.Q)("likes-count",e);g&&(0,m.ak)(g,a);(a=(0,m.Q)("dislikes-count",e))&&(0,m.ak)(a,b);if(b=(0,m.Q)("video-extras-sparkbar-likes",e))b.style.width=c+"%";if(c=(0,m.Q)("video-extras-sparkbar-dislikes",e))c.style.width=d+"%"};m.f=nG.prototype;m.f.dispose=function(){(0,m.y)(this.g);(0,m.eb)(this.b);this.b.length=0};m.f.iD=function(){this.fl()};m.f.Ut=function(a){window.document.title=1==a?"\u25b6 "+this.i:this.i};
m.f.jD=function(a){a=!!a;var b=(0,m.I)("watch7-container"),c=(0,m.I)("player"),d=(0,m.I)("watch7-sidebar");if(b&&c&&d){var e=(0,m.Nl)(d);if(a)(0,m.G)(b,"watch-wide"),(0,m.G)(c,"watch-playlist-collapsed"),(0,m.y)(this.g),this.g=(0,m.x)((0,m.r)(this.fl,this),e);else if((0,m.H)(b,"watch-wide"),(0,m.H)(c,"watch-playlist-collapsed"),this.fl(),(0,m.gl)(d),a=(0,m.I)("watch7-playlist-tray-container"))a=(0,m.Nl)(a),(0,m.x)(MC,a)}};
m.f.fl=function(){(0,m.y)(this.g);var a=(0,m.I)("player"),b=(0,m.I)("watch7-container");if(b&&a){var b=(0,m.nc)(b,"watch-wide"),c=(0,m.Ei)();b?(b=1540<=c.width&&1040<=c.height,(0,m.w)("ENABLE_AUTO_LARGE")&&b?((0,m.pj)(a,["watch-medium","watch-small"]),(0,m.G)(a,"watch-large")):((0,m.pj)(a,["watch-small","watch-large"]),(0,m.G)(a,"watch-medium"))):((0,m.pj)(a,["watch-medium","watch-large"]),(0,m.G)(a,"watch-small"))}};var qG,wG=[];var xG=[],yG=[];var zG=[];(0,m.l)("yt.www.watch.player.init",KE,void 0);
(0,m.l)("yt.www.watch.player.dispose",function(){(0,m.ao)(XE);(0,m.zm)(window,"beforeunload",iF);(0,m.eb)(cF);cF=[];(0,m.eb)(VE);VE=window.NaN;m.Hy.getInstance().ma("onlineReceiverChange",HE);IE&&(IE.removeEventListener("onRemoteReceiverSelected",JE),IE.removeEventListener("onReady",GE),IE=null);var a=(0,m.ty)();if(a){(0,m.ry)("API disposed");var b=m.my,c=(0,m.n)("yt.mdx.remote.debug.handlers_");(0,m.Da)(c,b);a.setReloadTabRequestHandler&&a.setReloadTabRequestHandler(m.da);a.removeReceiverListener("YouTube",
m.yy);(0,m.zy)(null)}m.wy=!1;PC=null;(0,m.zm)(window,"message",OC);(0,m.OA)();a=!1;LE&&(b=LE,b.removeEventListener("onReady",ME),b.removeEventListener("onStateChange",NE),b.removeEventListener("RATE_SENTIMENT",OE),b.removeEventListener("SHARE_CLICKED",PE),b.removeEventListener("SIZE_CLICKED",QE),b.removeEventListener("onError",RE),b.removeEventListener("WATCH_LATER_VIDEO_ADDED",SE),b.removeEventListener("WATCH_LATER_VIDEO_REMOVED",TE),b.removeEventListener("onAdStart",UE),LE.stopVideo&&(LE.stopVideo(),
a=!0));a||(a=(0,m.I)("movie_player"))&&a.stopVideo&&a.stopVideo();LE=null;nF=dF=!1;lF="";mF={};(0,m.eb)(YE);YE.length=0},void 0);(0,m.l)("yt.www.watch.player.seekTo",kF,void 0);(0,m.l)("yt.www.watch.player.play",function(){var a=LE;a&&a.playVideo()},void 0);(0,m.l)("yt.www.watch.player.pause",function(){var a=LE;a&&a.pauseVideo()},void 0);(0,m.l)("yt.www.watch.player.saveResumeOffset",hF,void 0);
(0,m.l)("yt.www.watch.player.handleEndPreview",function(a){var b=LE;b&&b.stopVideo&&b.stopVideo();(b=(0,m.I)("watch-checkout-offers"))&&(0,m.E)("ypc-init-purchase-for-container",b,a)},void 0);(0,m.l)("yt.tracking.social.onAdvertiserVideoView",m.fp,void 0);(0,m.l)("checkCurrentVideo",function(a,b,c){var d=(0,m.w)("VIDEO_ID");d&&d!=a&&(a=c?c:(0,m.ul)(window.location.href,{v:a,list:b}))&&(0,m.$b)(a)},void 0);
(0,m.l)("yt.www.watch.related.loadMore",function(){m.P.hide("watch-more-related-button");m.P.show("watch-more-related");kD(function(){(0,m.gl)((0,m.I)("watch-more-related"))})},void 0);(0,m.l)("yt.www.comments.initForm",vE,void 0);(0,m.l)("yt.www.thumbnaildelayload.classifyAndLoadVisibleImages",m.Gl,void 0);(0,m.l)("yt.www.watch.lists.loadThumbnails",MC,void 0);
(0,m.l)("yt.www.watch.lists.getState",function(){var a=[],b={},c=-1,d=[],e=tC;if(!e)return null;(0,m.C)(e.getElementsByTagName("li"),function(e,g){(0,m.nc)(e,zC)&&(c=g);var p=(0,m.F)(e,"video-id"),u=(0,m.F)(e,"video-username"),z=(0,m.F)(e,"video-title"),u={id:p,username:u,title:z},z=(0,m.F)(e,"video-clip-start"),D=(0,m.F)(e,"video-clip-end");a[g]=p;b[p]=u;d[g]={start:z,end:D}});var e=(0,m.Ge)(),g=m.Ie;return{author:(0,m.F)(g,"list-author"),autoPlay:e,clipRanges:d,index:c,listTitle:(0,m.F)(g,"list-title"),
listDescription:(0,m.F)(g,"list-description"),videoData:b,videoIds:a}},void 0);(0,m.l)("yt.www.watch.activity.getTimeSinceActive",m.Ee,void 0);(0,m.l)("yt.www.watch.activity.setTimestamp",m.De,void 0);(0,m.l)("yt.sharing.facebooktokenrefresh.finish",function(a){var b={session_token:(0,m.Vl)("social_connector_ajax"),service:"facebook"},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);(0,m.W)("/social_connector_ajax",{method:"POST",format:"JSON",da:{action_connect_service:1},ba:b})},void 0);
(0,m.l)("yt.abuse.invokeBotguard",function(){return fE?fE.invoke():null},void 0);(0,m.l)("yt.abuse.botguardInitialized",function(){return null!=fE},void 0);
(0,m.hb)((0,m.Zn)({name:"www/watch",deps:["www/common"],page:"watch",init:function(){KE();var a=(0,m.I)("watch7-action-buttons"),b=(0,m.I)("watch7-action-panels");vG=null;a&&b&&(vG=new VF(a,b));uG=new nG;(0,m.ze)();(0,m.M)(window.document,"keypress",gD);wD();qD();if((0,m.w)("BRANDED_BACKGROUND_IMAGE")||(0,m.w)("BRANDED_BACKGROUND_COLOR")){(0,m.R)((0,m.I)("guide-container"),"branded");var a=(0,m.I)("player"),b=(0,m.w)("BRANDED_BACKGROUND_IMAGE"),c=(0,m.w)("BRANDED_BACKGROUND_COLOR");b&&(a.style.background=
"transparent url("+b+") no-repeat center top",(0,m.uc)(window.document.body,"site-left-aligned")&&(a.style.backgroundPosition="left top"));c&&(a.style.backgroundColor=c)}a=(0,m.I)("watch7-sidebar");tG.push((0,m.X)(a,"click",xC,"related-action"));(0,m.w)("RADIO_ENTRYPOINT_RESUMES_CURRENTLY_PLAYING_VIDEO")&&tG.push((0,m.X)(a,"click",wC,"resumable-list"));wG.push((0,m.B)("prefetch",pG));(a=(0,m.w)("PLAYER_REFERENCE"))&&a.getPlayerState&&1==a.getPlayerState()?(0,m.tm)():wG.push((0,m.B)("player-state-change",
oG));m.gc&&(!window.document.documentMode||8>window.document.documentMode)&&xG.push((0,m.X)(window.document.body,"click",rG,"video-thumb"));(0,m.Xv)(1);a=(0,m.w)("WATCH_RELATED_DELAY");b=!!(0,m.Q)("guide-module-loading");oF(b,a);zG.push((0,m.B)("ypc-purchase-success",sG));(0,m.Wv)();(0,m.w)("FACEBOOK_TOKEN_REFRESH_ENABLED")&&(a=(0,m.I)("facebook_token_refresh_iframe"),b=(0,m.w)("FACEBOOK_TOKEN_REFRESH_URL"),a&&(0,m.Jf)("facebook_token_refresh")!=b&&((0,m.Gf)("facebook_token_refresh",b,3600),a.src=
b))},dispose:function(){vG&&((0,m.Ka)(vG),vG=null);uG&&((0,m.Ka)(uG),uG=null);(0,m.zm)(window.document,"keypress",m.Be);(0,m.zm)(window.document,"click",m.Ce);m.Ae=-2;(0,m.zm)(window.document,"keypress",gD);null!=window.adModuleLoaded&&(0,m.Qm)("adModuleLoaded");(0,m.y)(dE);AD&&(AD=null);xD&&(xD.dispose(),xD=null);zD=OD=ND=MD=null;KD=cE=!1;if(LD){for(var a=LD.length-1;0<=a;a--)(0,m.Qm)(LD[a]);LD=[]}(0,m.Zy)();(0,m.Qe)(0);(0,m.T)(rD);rD.length=0;if((a=(0,m.We)())&&a.getApiInterface){a.removeEventListener("onCueRangeEnter",
LC);a.removeEventListener("onReady",fD);for(var b=5;0<b;b--)a.removeCueRange("NEAR_END"+b)}(0,m.eb)(sD);sD.length=0;m.Ve&&(0,m.H)(m.Ve,"scrolled");m.Ue=null;m.He=m.Oe=m.Te=!1;m.Ie=BC=m.Je=$C=bD=tC=m.Re=m.Ve=null;zC="";m.Me=!1;m.Pe&&((0,m.y)(m.Pe),m.Pe=null);(a=(0,m.I)("guide-container"))&&(0,m.V)(a,"branded");if(a=(0,m.I)("player"))a.style.background="";tG&&((0,m.T)(tG),tG=[]);qG=!1;(0,m.eb)(wG);wG.length=0;(0,m.T)(xG);xG.length=0;(0,m.eb)(yG);yG.length=0;for(var c in qF)(0,m.y)(qF[c]);qF={};(0,m.T)(rF);
wE&&(wE.destroy(),wE=null);wF&&(wF.destroy(),wF=null);(0,m.yA)();(0,m.T)(xF);xF.length=0;(0,m.eb)(zG)}}));})(_yt_www);
